SRC_DIR = src
#MODULE_VERSION = v1.12.2
MODULE_VERSION = v7.99.1
#MODULE_REPO = https://github.com/redistimeseries/redistimeseries
MODULE_REPO = https://github.com/redislabsdev/RedisTimeSeries
TARGET_MODULE = $(SRC_DIR)/bin/$(FULL_VARIANT)/redistimeseries.so

include ../common.mk
