SRC_DIR = src
#MODULE_VERSION = v2.8.2
MODULE_VERSION = v7.99.1
#MODULE_REPO = https://github.com/redisbloom/redisbloom
MODULE_REPO = https://github.com/redislabsdev/RedisBloom
TARGET_MODULE = $(SRC_DIR)/bin/$(FULL_VARIANT)/redisbloom.so

include ../common.mk
